# Database Configuration
# Copy file này thành config.properties và điền thông tin thực của bạn
# File này KHÔNG được commit lên Git (đã được thêm vào .gitignore)

db.url=jdbc:mysql://mysql-24b3aff1-vnu-8ca6.k.aivencloud.com:15190/daugia?sslMode=REQUIRED&serverTimezone=Asia/Ho_Chi_Minh
db.user=avnadmin
db.password=AVNS_z7YUU9pQJHKGFnNqf8-
